services:
  # Serviço de desenvolvimento
  app-dev:
    image: node:20-alpine
    container_name: icv-dev
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  # Serviço de produção
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: icv-prod
    ports:
      - "80:80"
    restart: unless-stopped
    # Descomente para personalizar variáveis de ambiente em produção se necessário
    # environment:
    #   - NODE_ENV=production
    
volumes:
  node_modules: 